var generatedPattern = [];

var userClickedPattern = [];

var buttonColor = ["red", "blue", "green", "yellow"];

var level = 0;

var started = false;

// for starting the game by a keypress using the "keypress" event listener
$("body").on("keypress",function () {
  if(!started) {
    generatePattern();
    $("#level-title").text("level " + level);
    started = true;
  }
});

// for listening to the user clicks on the buttons and changing the animation
$(".btn").on("click",function () {
  var userPressedButton = $(this).attr("id");

  //play the sound for the button clicked
  playSound(userPressedButton);

  $("#"+ userPressedButton).addClass("pressed");

  setTimeout(function () {
      $( "#" + userPressedButton).removeClass("pressed");
  },100);

  userClickedPattern.push(userPressedButton);

  validation(userClickedPattern.length - 1);
});


//to generate a random color each time it is called
function generatePattern() {

  level++;
  $("#level-title").text("level  " + level );

  var randomNumber = Math.floor(Math.random() * 3) + 1; //random num b/w 0-3
  var randomChosenColor = buttonColor[randomNumber];

  //playing the sound and adding animation to the random button generated by a randomNumber
  $("#" + randomChosenColor).fadeIn(100).fadeOut(100).fadeIn(100);
  playSound(randomChosenColor);

  //storing the pattern generated to verify it at a later time
  generatedPattern.push(randomChosenColor);

}

function validation (gameLevel) {
  if(generatedPattern[gameLevel] === userClickedPattern[gameLevel]) {

      if(generatedPattern.length === userClickedPattern.length) {

        userClickedPattern = [];
        setTimeout(function () {
          generatePattern();
        },1000);
      }
  }else {

    $("body").addClass("game-over");
    $("#level-title").text("Game Over, Press Any Key to Restart");
    setTimeout(function() {
      $("body").removeClass("game-over");
    },200);
    started = false;
    generatedPattern = [];
    userClickedPattern = [];
    level = 0;
  }
}

//for playing the sound for the buttons
function playSound(name) {
    var sound = new Audio("sounds/" + name + ".mp3");
    sound.play();
  }
